from django.db import models
from django.contrib.auth.models import User
from .storages import OverwriteStorage

class Cashbook(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    cashbook_date=models.DateField()
    particular=models.CharField(max_length=50)
    cashbook_amount=models.IntegerField()
    transection_type=models.CharField(max_length=10,default=None)

class Bilty(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    mob=models.CharField(max_length=10,null=True,blank=True)
    invoiceno=models.CharField(max_length=20)
    truckno=models.CharField(max_length=100,default=None)
    date=models.DateField()
    consignor_details=models.CharField(max_length=500)
    consignee_details=models.CharField(max_length=500)
    lr_no=models.IntegerField()
    rate=models.FloatField()
    weight=models.FloatField()
    fair=models.FloatField()
    advance=models.IntegerField()
    recived_money=models.IntegerField()
    goods_description=models.CharField(max_length=100,blank=True,null=True,default=None)

class Document(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    truckno=models.CharField(max_length=100,default=None)
    puc=models.FileField(upload_to='docs/',null=True,blank=True,default=None,storage=OverwriteStorage())
    insurance=models.FileField(upload_to='docs/',null=True,blank=True,default=None,storage=OverwriteStorage())
    rc=models.FileField(upload_to='docs/',null=True,blank=True,default=None,storage=OverwriteStorage())
    india_permit=models.FileField(upload_to='docs/',null=True,blank=True,default=None,storage=OverwriteStorage())
    state_permit=models.FileField(upload_to='docs/',null=True,blank=True,default=None,storage=OverwriteStorage())
    fitness=models.FileField(upload_to='docs/',null=True,blank=True,default=None,storage=OverwriteStorage())
    decleration=models.FileField(upload_to='docs/',null=True,blank=True,default=None,storage=OverwriteStorage())
    danda=models.FileField(upload_to='docs/',default=None,storage=OverwriteStorage())
    def __str__ (self):
        return self.truckno
    def delete(self, *args, **kwargs):
        self.puc.delete()
        self.insurance.delete()
        self.rc.delete()
        self.india_permit.delete()
        self.state_permit.delete()
        self.fitness.delete()
        self.decleration.delete()
        self.danda.delete()
        super().delete(*args,**kwargs)

class Loan_Record(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    truckno=models.CharField(max_length=15,default=None)
    owner_name=models.CharField(max_length=50)
    loan_amount=models.FloatField()
    interest_rate=models.FloatField()
    loan_duration=models.IntegerField()
    installment_amount=models.FloatField(null=True)
    installment_date=models.DateField()
    month_paid=models.IntegerField(default=0,blank=True)
    months=models.IntegerField(null=True,blank=True)
    inlineRadioOptions=models.CharField(max_length=5,null=True,blank=True)
 
class TripProfile(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    truckno=models.CharField(max_length=50,default=None)
    company_name=models.CharField(max_length=200,default=None)
    pickup=models.CharField(max_length=100,default=None)
    diesel=models.FloatField()
    trip_kilometers=models.FloatField()
    trip_expenses=models.CharField(max_length=500,default=None)
    toll_tax=models.FloatField()
    fair=models.FloatField()
    balance=models.FloatField()
    unloading_amount=models.FloatField()
    balance_collected=models.FloatField()
    unloading_description=models.TextField(null=True,blank=True)
    destination=models.CharField(max_length=100,default=None)
    destination2=models.CharField(max_length=100,null=True,blank=True)
    destination3=models.CharField(max_length=100,null=True,blank=True)
    destination4=models.CharField(max_length=100,null=True,blank=True)
    destination5=models.CharField(max_length=100,null=True,blank=True)

    delivery_date=models.DateField()
    delivery_date2=models.DateField(null=True,blank=True)
    delivery_date3=models.DateField(null=True,blank=True)
    delivery_date4=models.DateField(null=True,blank=True)
    delivery_date5=models.DateField(null=True,blank=True)

    good_type=models.CharField(max_length=200,default=None)
    good_type2=models.CharField(max_length=200,null=True,blank=True)
    good_type3=models.CharField(max_length=200,null=True,blank=True)
    good_type4=models.CharField(max_length=200,null=True,blank=True)
    good_type5=models.CharField(max_length=200,null=True,blank=True)

    weight=models.FloatField(default=0)
    weight2=models.FloatField(null=True,blank=True,default=0)
    weight3=models.FloatField(null=True,blank=True,default=0)
    weight4=models.FloatField(null=True,blank=True,default=0)
    weight5=models.FloatField(null=True,blank=True,default=0)
    
    rate=models.FloatField(default=0)
    rate2=models.FloatField(null=True,blank=True,default=0)
    rate3=models.FloatField(null=True,blank=True,default=0)
    rate4=models.FloatField(null=True,blank=True,default=0)
    rate5=models.FloatField(null=True,blank=True,default=0)

class TruckMaintenance(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    truckno=models.CharField(max_length=100,default=None)
    service_date=models.DateField()
    service_km=models.FloatField()
    service_details=models.CharField(max_length=1000)
    service_by=models.CharField(max_length=200)
    service_cost=models.FloatField() 
    service_note=models.CharField(max_length=500,null=True,blank=True)

class TyreRecord(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    truckno=models.CharField(max_length=100,default=None)
    tyre_date=models.DateField()
    tyre_brand=models.CharField(max_length=200)
    tyre_model=models.CharField(max_length=100)
    tyre_number=models.CharField(max_length=100)
    tyre_price=models.FloatField()
    km_reading=models.FloatField()
    tyre_status=models.CharField(max_length=30)
    tyre_description=models.CharField(max_length=500,blank=True,null=True,default=None)    