# Generated by Django 3.1.3 on 2020-11-15 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transportapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckno', models.CharField(default=None, max_length=50)),
                ('company_name', models.CharField(default=None, max_length=200)),
                ('pickup', models.CharField(default=None, max_length=100)),
                ('diesel', models.FloatField()),
                ('trip_kilometers', models.FloatField()),
                ('trip_expenses', models.CharField(default=None, max_length=500)),
                ('toll_tax', models.FloatField()),
                ('fair', models.FloatField()),
                ('balance', models.FloatField()),
                ('unloading_amount', models.FloatField()),
                ('balance_collected', models.FloatField()),
                ('unloading_description', models.TextField(blank=True, null=True)),
                ('destination', models.CharField(default=None, max_length=100)),
                ('destination2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('destination3', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('destination4', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('destination5', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('delivery_date', models.DateField()),
                ('delivery_date2', models.DateField(blank=True, null=True)),
                ('delivery_date3', models.DateField(blank=True, null=True)),
                ('delivery_date4', models.DateField(blank=True, null=True)),
                ('delivery_date5', models.DateField(blank=True, null=True)),
                ('good_type', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('weight', models.FloatField(default=0)),
                ('weight2', models.FloatField(blank=True, default=0, null=True)),
                ('weight3', models.FloatField(blank=True, default=0, null=True)),
                ('weight4', models.FloatField(blank=True, default=0, null=True)),
                ('weight5', models.FloatField(blank=True, default=0, null=True)),
                ('rate', models.FloatField(default=0)),
                ('rate2', models.FloatField(blank=True, default=0, null=True)),
                ('rate3', models.FloatField(blank=True, default=0, null=True)),
                ('rate4', models.FloatField(blank=True, default=0, null=True)),
                ('rate5', models.FloatField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
