# Generated by Django 3.1.3 on 2020-11-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0006_auto_20201117_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripprofile',
            name='destination3',
            field=models.CharField(blank=True, default='YYYY-MM-DD', max_length=100, null=True),
        ),
    ]
