# Generated by Django 3.1.3 on 2020-11-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0007_auto_20201118_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripprofile',
            name='destination3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
