# Generated by Django 3.1.3 on 2020-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0008_auto_20201118_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripprofile',
            name='delivery_date2',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
